[package]
name = "matrices"
version = "0.1.0"
edition = "2021"

[dependencies]
bit-vec = "0.8.0"
bitvec = "1.0.1"
custom_error = "1.9.2"
itertools = "0.14.0"
katex = "0.4.6"
paste = "1.0.15"
rand = "0.9.0"



