name: Rust

on:
  push:
    branches: [ "**" ]  # Runs on every branch
  pull_request:
    branches: [ "**" ]  # Runs for PRs on every branch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust nightly
      run: |
        rustup update nightly
        rustup default nightly
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
